spring:
  application:
    name: product-info-service
  profiles:
    active: production

info:
  app:
    name: "e-commerce/product-info-service"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: "*"
